Nextcloud backup: allow subdir
opnsense/core pull request #4077
Opened 2020-04-30 06:12 UTC by maxxer

Fixes #3988

2020-04-30 06:44 UTC, AdSchellevis commented
@fabianfrz do you have time to spin this for a test?

2020-05-03 19:11 UTC, fabianfrz commented
@AdSchellevis crashes immediately:

Fatal error: Uncaught Error: Call to undefined function OPNsense\Backup\basedir() in /usr/local/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php:147 Stack trace: #0 /usr/local/www/diag_backup.php(286): OPNsense\Backup\Nextcloud->backup() #1 {main} thrown in /usr/local/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php on line 147

2020-05-03 19:31 UTC, fabianfrz commented
log after fixing the issue by replacing it by basename(), opnsense/backup as file name:

config[60397]: Error while fetching filelist from Nextcloud

```json
{
  "url":"https:\/\/nextcloud.test\/remote.php\/dav\/files\/opnsensebkp\/Backup",
  "content_type":"text\/html; charset=UTF-8",
  "http_code":404,
  "header_size":1220,
  "request_size":205,
  "filetime":-1,
  "ssl_verify_result":0,
  ...
}
```

Tested on OPNsense 20.1.r_12 (amd64/LibreSSL) - I don't think somebody changed the nextcloud code inbetween

2020-05-04 05:07 UTC, maxxer commented
Hi @fabianfrz thanks for the feedback. 

About the last issue, one question: does `opnsensebkp` directory exist on your Nextcloud? Because indeed the plugin doesn't create all the path to the backup dir, I left the original behaviour that will create just the last one (`Backup` in your example). Is it expected differently?

2020-05-04 05:21 UTC, maxxer commented
I'm sorry for the misspelled function name, I meant to use `dirname` but accidentally copied the wrong file to git :(

2020-05-05 16:12 UTC, fabianfrz commented
now the php error is gone but the backup still fails.

2020-05-05 17:18 UTC, maxxer commented
Does the parent directory exist?

2020-05-05 17:22 UTC, fabianfrz commented
nope, but that is what the code is expected to do, create the full directory hierarchy if missing.

2020-05-05 17:29 UTC, maxxer commented
Ok, I will implement that. I asked two comments ago but got not answer...

2020-05-09 19:35 UTC, fabianfrz commented
Sorry I forgot the answer but if you read the source, there is already MKCOL implemented which is doing this so yes, it is the current behaviour.

2020-05-23 21:23 UTC, maxxer commented
I've updated the patch and merge against current master, I hope it's fine now

2020-09-04 03:11 UTC, maxxer commented
Any chance to get another review?

2020-12-29 17:57 UTC, hasechris commented
Hii,

> Any chance to get another review?
@fabianfrz could you please review this merge?

Thanks in advance

2020-12-29 21:40 UTC, fabianfrz requested changes
I found some improvements for the models but if this changes are in the PR, I can give it a test run.

2020-12-29 21:40 UTC, fabianfrz commented on src/opnsense/mvc/app/models/OPNsense/Backup/NextcloudSettings.xml
> +            <mask>/^[\w\-][\w\-\/]+[\w\-]$/</mask>
I think this regex is wrong. I think you meant something like this:
```suggestion
            <mask>/^([\w%+\-]+\/)*[\w+%\-]+$/</mask>
```
This means the first part is entirely optional (allows names like 'a') and if it is in place, It allows names like 'aa'.

You can test regexes on rubular if you want. Here are some examples;
```
abc
a/b/%20+/aa/xaajsdkjfallsdjfas
a/b/%20+/aa/xaajsdkjfallsdjfas%20
a/b/%20+/aa/xaajsdkjfallsdjfas+
a//b
```
The last one does not match so the double slash is detected as well! Important things: % is used for encoding using hex like %20 for space. Also + is used for spaces so this characters should be allowed as well.

2020-12-29 21:40 UTC, fabianfrz commented on src/opnsense/mvc/app/models/OPNsense/Backup/NextcloudSettings.xml
> +    <version>1.0.1</version>
this is not required

2021-01-02 09:40 UTC, fabianfrz commented
Tested now successfully:

![Screenshot_20210102_103815](https://user-images.githubusercontent.com/3713914/103454681-b18e1580-4ce6-11eb-8347-00595aa7b6ed.png)
![Screenshot_20210102_103916](https://user-images.githubusercontent.com/3713914/103454691-cf5b7a80-4ce6-11eb-8c04-ffff346ea813.png)
![Screenshot_20210102_103959](https://user-images.githubusercontent.com/3713914/103454698-e601d180-4ce6-11eb-9ceb-c7bd5f806dea.png)

2021-01-02 09:52 UTC, AdSchellevis commented
@maxxer @fabianfrz thanks! I will merge it to master

2021-01-02 09:53 UTC, merged