Firewall/Scrub: Display interface descriptions
opnsense/core pull request #5433
Opened 2021-12-27 15:00 UTC by vnxme

This PR is a quick fix of an issue on the Firewall/Setting/Normalization page. The page shows interface names (e.g. opt1) in the Interfaces column of the Detailed settings table, while the corresponding editing page shows interface descriptions. I suggest we convert interface names to descriptions using the approach taken from firewall_scrub_edit.php.

2021-12-27 16:01 UTC, AdSchellevis requested changes
left some remarks in the PR, when more than a single interface is selected the longer descriptions do have a downside in terms of readability.

2021-12-28 08:04 UTC, vnxme commented on src/www/firewall_scrub.php
> +                    foreach ($scrubEntryInterfaceNames as $scrubEntryInterfaceName) {
Not sure whether it really simplifies anything. Done in 2969438.

2021-12-28 08:04 UTC, vnxme commented on src/www/firewall_scrub.php
> +                            $scrubEntryInterfaceDescrs[] = $configured_interfaces[$scrubEntryInterfaceName]['descr'];
Thanks, agree, taken into account in 2969438.

2021-12-28 08:04 UTC, vnxme commented on src/www/firewall_scrub.php
> +                    <td><?=$scrubEntryInterfaceText;?></td>
Again, it seems to me you suggest saving a piece of paper (or a line of file, to be precise). Done in 2969438.

2021-12-28 08:07 UTC, AdSchellevis commented on src/www/firewall_scrub.php
> +                    <td><?=$scrubEntryInterfaceText;?></td>
@vnxme simple, smaller code snippets are easier to read and remember. thanks for taking care!

2021-12-28 08:07 UTC, merged