Update ipsec.widget.php
opnsense/core pull request #6912
Opened 2023-10-04 18:08 UTC by Monviech

https://github.com/opnsense/core/issues/6889

This change attempts to solve the problem of users having multiple IP addresses as leases and being counted per leased IP.
- Only "user" are counted now
- Each "user" can have several "lease"
- Each "lease" can have an individual online or offline status
- A user is online when at least one "lease" is "online = true"

The code can be tested with this sample data. It can be placed in line 46 and populates the variable $ipsec_leases = []

```
$ipsec_leases = array(
    array(
        'pool' => 'pool-roadwarrior-ipv4',
        'address' => '172.16.203.1',
        'online' => true,
        'user' => 'user1@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv4',
        'address' => '172.16.203.2',
        'online' => false,
        'user' => 'user2@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv4',
        'address' => '172.16.203.3',
        'online' => true,
        'user' => 'user3@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv4',
        'address' => '172.16.203.4',
        'online' => true,
        'user' => 'user5@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv6',
        'address' => 'fd00:abcd:1234:1::1',
        'online' => false,
        'user' => 'user1@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv6',
        'address' => 'fd00:abcd:1234:1::2',
        'online' => false,
        'user' => 'user1@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv6',
        'address' => 'fd00:abcd:1234:1::3',
        'online' => true,
        'user' => 'user1@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv6',
        'address' => 'fd00:abcd:1234:2::1',
        'online' => false,
        'user' => 'user2@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv6',
        'address' => 'fd00:abcd:1234:2::2',
        'online' => false,
        'user' => 'user3@vpn1'
    ),
    array(
        'pool' => 'pool-roadwarrior-ipv6',
        'address' => 'fd00:abcd:1234:3::1',
        'online' => true,
        'user' => 'user4@vpn1'
    )
);
```
The result will look like this:

![grafik](https://github.com/opnsense/core/assets/79600909/38eba6b1-5a94-4a0d-87ed-573caa1d4643)

All users that have at least one online lease will be counted towards "Mobile Users". In the above sample data, user2@vpn1 has two offline leases, which means the user counts as not connected. All other users have at least one or multiple online leases, which makes them count as online.

![grafik](https://github.com/opnsense/core/assets/79600909/0d82d86e-3621-4d13-b7c1-3ab3f723a941)

I think this is the best variant, since it adds new functionality while also retaining all old functionality. :)

2023-10-04 18:36 UTC, AdSchellevis requested changes
Looks good, some small remarks

2023-10-04 18:36 UTC, AdSchellevis commented on src/www/widgets/widgets/ipsec.widget.php
> +$aggregated_data = array();
`$aggregated_data = [];` is a bit shorter, the `array()` construction is used less often in our newer code.

2023-10-04 18:36 UTC, AdSchellevis commented on src/www/widgets/widgets/ipsec.widget.php
> +    if (!isset($aggregated_data[$user])) {
It's shorter to use the `$lease['user']` without storing it first (e.g. `if (!isset($aggregated_data[$lease['user']])) {`), although for `$user` I can understand it if one would find it more readable, the address and online fields are certainly less useful to store first (just adding `$lease` to `$aggregated_data[$user]` might also be an option, the extra user field is not used anyway.

2023-10-04 18:36 UTC, AdSchellevis commented on src/www/widgets/widgets/ipsec.widget.php
> +        if ($lease['online']) {
I would push this one in the other loop, so you only have to travers `$ipsec_leases` once.

2023-10-04 18:46 UTC, Monviech commented
@AdSchellevis you're always so fast, thanks! I'm happy you reviewed the code and I will improve the parts you suggested as soon as I can. If I can't figure it out I'll ask for help. Have a nice evening ^^

2023-10-04 18:49 UTC, AdSchellevis commented
@Monviech it's a bit of a sport I guess ;) thanks for baring with me

2023-10-05 08:36 UTC, Monviech commented
@AdSchellevis 
I have revised the code and I tested it with my fake data above, and also with real data on a production firewall. The widget still does the same job for me. Thank you for the hints to make it more efficient.

2023-10-05 09:05 UTC, merged

2023-10-05 09:05 UTC, AdSchellevis commented
@Monviech looks good, thanks!